export const LayerSet = [
  {
    name: "Flood Inundation",
    description: "Flood Inundation Map layer",
    icon: "https://images.theconversation.com/files/443262/original/file-20220129-17-189cjvd.png?ixlib=rb-1.1.0&q=45&auto=format&w=250&fit=clip",
    layerID: "flood-ae3jmx",
    iconColor: "#B786E8",
    legend:
      "Flood inundation areas and the inundation depth caused by a “planned scale” of rainfall, which is assumed to be about once every 10 to 100 years",
    hazardZone: true,
    category: "Hazards",
  },
  {
    name: "High Tide",
    description: "High tide map layer",
    icon: "https://images.theconversation.com/files/443260/original/file-20220129-13-vcoz11.jpg?ixlib=rb-1.1.0&q=45&auto=format&w=1000&fit=clip",
    layerID: "tides-90iztk",
    iconColor: "#E7AF78",
    legend:
      "Assumed storm surge inundation areas and their inundation depths (GIS)",
    hazardZone: true,
    category: "Hazards",
  },
  {
    name: "Tsunami",
    description: "Tsunami risk map layer",
    icon: "https://images.pexels.com/photos/4603456/pexels-photo-4603456.jpeg?auto=compress&cs=tinysrgb&w=60&h=50&dpr=2",
    layerID: "tsunami-518f7t",
    iconColor: "salmon",
    legend:
      "Assumed tsunami inundation areas and their maximum inundation depth (GIS)",
    hazardZone: true,
    category: "Hazards",
  },
  {
    name: "Active Faults",
    description: "Active Fault Lines Map layer",
    icon: "https://www.researchgate.net/publication/340298211/figure/fig6/AS:875085455953922@1585648039547/Tectonic-map-of-Japan-Thin-black-lines-denote-active-faults-Gray-lines-denote-plate.jpg",
    layerID: "faults-ap125y",
    iconColor: "red",
    legend:
      "Active faults and their lengths (Geological Survey of Japan, National Institute of Advanced Industrial Science and Technology)",
    hazardZone: true,
    category: "Hazards",
  },
  {
    name: "Sediment",
    description: "Sediment Inundation Map layer",
    icon: "https://images.pexels.com/photos/5753028/pexels-photo-5753028.jpeg?auto=compress&cs=tinysrgb&w=50&h=50&dpr=2",
    layerID: "sediment-housecollapse-3mr1co",
    iconColor: "brown",
    legend:
      "Sediment disaster areas and the type of disaster and designated warning area (GIS)",
    hazardZone: true,
    category: "Hazards",
  },
  {
    name: "Volcanoes",
    description: "Volcanoes Map layer",
    icon: "https://images.pexels.com/photos/3408353/pexels-photo-3408353.jpeg?auto=compress&cs=tinysrgb&w=50&h=50&dpr=2",
    layerID: "volcano-heat",
    iconColor: "#A21A31",
    legend:
      "Location of active volcanoes in Japan (Japan Meterological Agency)",
    hazardZone: true,
    category: "Hazards",
  },
  {
    name: "Business Areas",
    description: "Business Area Map Layer",
    icon: "https://images.pexels.com/photos/668300/pexels-photo-668300.jpeg?auto=compress&cs=tinysrgb&w=60&h=60&dpr=2",
    layerID: "business-areas",
    iconColor: "royalblue",
    legend: "Business Area Zones",
    category: "Land Zoning",
  },
  {
    name: "Industrial Areas",
    description: "Industrial Areas Map Layer",
    icon: "https://images.pexels.com/photos/247763/pexels-photo-247763.jpeg?auto=compress&cs=tinysrgb&w=60&h=50&dpr=2",
    layerID: "industrial-areas",
    iconColor: "#FFD412FF",
    legend: "Industrial Area Zones",
    category: "Land Zoning",
  },
  {
    name: "Residential Areas",
    description: "Industrial Areas Map Layer",
    icon: "https://images.pexels.com/photos/2187605/pexels-photo-2187605.jpeg?auto=compress&cs=tinysrgb&w=60&h=60&dpr=2",
    layerID: "residential-areas",
    iconColor: "#24A791",
    legend: "Residential Area Zones",
    category: "Land Zoning",
  },
  {
    name: "Military Bases",
    description: "Military Bases Map Layer",
    icon: "https://images.pexels.com/photos/11823877/pexels-photo-11823877.jpeg?auto=compress&cs=tinysrgb&w=60&h=50&dpr=2",
    layerID: "military-bases",
    iconColor: "#314669",
    legend: "Military bases map marker",
    category: "Land Marks",
  },
  {
    name: "Oil Refineries",
    description: "Oil Refineries Map Layer",
    icon: "https://images.pexels.com/photos/6060191/pexels-photo-6060191.jpeg?auto=compress&cs=tinysrgb&w=60&h=50&dpr=2",
    layerID: "oil-refineries",
    iconColor: "#f59d22",
    legend: "Oil refinery",
    category: "Land Marks",
  },
  {
    name: "Nuclear Power Plant",
    description: "Nuclear Power plant Map layer",
    icon: "https://images.pexels.com/photos/459728/pexels-photo-459728.jpeg?auto=compress&cs=tinysrgb&w=60&h=50&dpr=2",
    layerID: "nuclear-powerplant",
    iconColor: "black",
    legend: "Nuclear power plant",
    category: "Power Generation",
  },
  {
    name: "Submarine Landing Cables",
    description: "Submarine Landing Cables Map Layer",
    icon: "https://blog.advantagecg.com/hubfs/Imported_Blog_Media/Submarine%20Map.png",
    layerID: "submarine-landing-icons",
    iconColor: "darkblue",
    legend: "Submarine Landing Cables",
    category: "Point of Interest",
  },
  {
    name: "Transmission Lines",
    description: "Transmission Lines Layer",
    icon: "https://images.pexels.com/photos/8246779/pexels-photo-8246779.jpeg?auto=compress&cs=tinysrgb&w=60&h=50&dpr=2",
    layerID: "transmission-lines",
    iconColor: "blue",
    legend:
      "Transmission line cables and coordinates for Kyushu and Toyama only",
    category: "Power Transmission",
  },
  {
    name: "Electrical Substations",
    description: "Electrical Substations layer",
    icon: "https://images.unsplash.com/photo-1658870901055-665c9621d7a9?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=100&q=70",
    layerID: "electrical-substations",
    iconColor: "#21E2C2",
    legend: "Location of Electric Substations for Kyushu and Toyama only",
    category: "Power Transmission",
  },
];
